### ISSUE TITLE
Fix Code coverage

### ISSUE THREAD

**Issue by arkadiuszbachorski** [StanfordBDHG/ENGAGE-HF-Web-Frontend#6]
### Problem

Code coverage doesn't report coverage for whole repo correctly

### Solution

Code coverage should take whole repository into consideration

### Additional context

https://github.com/StanfordBDHG/ENGAGE-HF-Web-Frontend/pull/5#discussion_r1635825405

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
@arkadiuszbachorski I addressed this in a small PR that improves the jest configuration to properly report coverage for all typescript files. We might want to tweak this in #5 if we should exclude/include any additional files and probably pull that over to the NextJSTemplate once this is baked in: https://github.com/StanfordBDHG/NextJSTemplate/issues/29
